### ISSUE TITLE
Call stack is exhausted in cross-reference module

### ISSUE THREAD

**Issue by takajun** [bminer/module-concat#3]
I created the following 3 js files.
**a.js**

```
var b = require('./b');
var c = require('./c');

console.log('call func_b1');
b.func_b1();
console.log('call func_c1');
c.func_c1();
```

**b.js**

```
var c = require('./c');

function func_b1() {
  console.log('func_b1');
  c.func_c2();
}
exports.func_b1 = func_b1;

function func_b2() {
  console.log('func_b2');
}
exports.func_b2 = func_b2;
```

**c.js**

```
var b = require('./b');

function func_c1() {
  console.log('func_c1');
  b.func_b2();
}
exports.func_c1 = func_c1;

function func_c2() {
  console.log('func_c2');
}
exports.func_c2 = func_c2;
```

I concatenated a.js and it is succeeded without no issue, but I got the following error on running the concatenated js,

---

Z:\concat.js:77
var exports = {}, module = {"exports": exports};
^

RangeError: Maximum call stack size exceeded
    at Object.__modules.(anonymous function) (Z:\concat.js:77:1)
    at __require (Z:\concat.js:18:39)
    at Object.__modules.(anonymous function) (Z:\concat.js:59:9)
    at __require (Z:\concat.js:18:39)
    at Object.__modules.(anonymous function) (Z:\concat.js:78:9)
    at __require (Z:\concat.js:18:39)
    at Object.__modules.(anonymous function) (Z:\concat.js:59:9)
    at __require (Z:\concat.js:18:39)
    at Object.__modules.(anonymous function) (Z:\concat.js:78:9)
    at __require (Z:\concat.js:18:39)

---

**Comment by bminer** [comment]
Interesting... looking into this now.

**Comment by bminer** [comment]
Figured out the issue.  Since `b` requires `c` and `c` requires `b`, we have an infinite `require` loop.  I'm wondering how Node works this out internally, and I'll just mimic that behavior in node-module-concat.  Thanks for submitting this issue!

**Comment by takajun** [comment]
Thanks. It works fine.
